id: P79882EB4
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN10545
  title: སྡོམ་པ་གསུམ་གྱི་རྣམ་གཞག་སྟོན་པའི་གཞུང་གཅེས་བཏུས།
  volumes:
    8bff104346434b369738889176aaa9c6:
      image_group_id: I3CN10547
      title: ''
      base_file: v001.txt
  author: ''
